# conda env create --file workflow/envs/batch-infer.yaml --prefix /opt/miniforge3/envs/batch-infer-env
# conda env remove --prefix /opt/miniforge3/envs/batch-infer-env
name: batch-infer-env
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- awscli
- aria2
- pandas
- snakemake-minimal==8.16  # https://github.com/snakemake/snakemake/issues/3019
- snakemake-executor-plster-generic for native v8 SLURM supportugin-slurm  # replaces clu
- snakemake-executor-plugin-cluster-generic  # kept for colabfold target compatibility
- wget

