cluster: True 
executor: slurm
conda-prefix: pipeline
jobscript: pipeline.sh
use-conda: True 
conda-frontend: conda
jobs: 80
scheduler: greedy
verbose: True 

default-resources:
 runtime: 1h
 time: 30:00:00
 slurm_account: ibarbier
 mem: 4G
 cpus_per_task: 80
 slurm_partition: slurm

