
executor: slurm
slurm-status-command: squeue
slurm-status-attempts: 50

conda-prefix: pipeline
jobscript: pipeline.sh
use-conda: True 
conda-frontend: conda
jobs: 80
scheduler: greedy
verbose: True 

default-resources:
 account: ibarbier 
 time: 00:30:00
 mem: 4G
 cpus_per_task: 80
 gres: nvidia_rtx_pro_6000_blackwell_workstation_edition:2
 gpus: 1 



