
executor: slurm
slurm-status-command: squeue
#slurm-status-attempts: 35

conda-prefix: pipeline
jobscript: pipeline.sh
use-conda: True 
conda-frontend: conda
scheduler: greedy
jobs: 80
verbose: True 

#default-resources:
 #account: ibarbier 
 #time: 00:30:00
 #mem: 4G
 #cpus_per_task: 80
 #gpus: 1
 #qos: sbatch



