
#/mnt/ibcportal/sgaussmann/alphafold3/p53_interactome_screen/.snakemake-local/runtime-profile

#opt/ibc/alphafold3/batch-infer/current/workflow/profiles/local

#alphafold3_predictions_multigpu

#--export=ALL,TMPDIR=__TMPDIR__

executor: cluster-generic

cluster-generic-submit-cmd:
  SMK_RULE_DIR=__CLUSTER_LOG_ROOT__/`date +"%y-%m-%d"`/{rule} &&
  SMK_WILDCARDS=`echo -n '{wildcards}' | sed -e 's#/#-#g'` &&
  SMK_SLURM_EXTRA=`echo -n '{resources.slurm_extra}' | sed -e 's/%/:/g'` &&
  SMK_SLURM_GID_OPTION="__SLURM_GID_OPTION__"  &&
  mkdir -p $SMK_RULE_DIR &&
  sbatch
    --job-name={rule}:{wildcards}
    --ntasks={threads}
    --mem-per-cpu=`expr {resources.mem_mb} / {threads}`
    --time={resources.runtime}
    $SMK_SLURM_GID_OPTION
    --output=$SMK_RULE_DIR/{rule}:$SMK_WILDCARDS-%j.txt
    $SMK_SLURM_EXTRA
    --parsable
    

cluster-generic-status-cmd: __STATUS_CMD__
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 1000
default-resources:
  runtime: 1h
  mem_mb: 1024
  disk_mb: 51200
  slurm_extra: "''"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 4
keep-going: true
rerun-incomplete: true
printshellcmds: true
scheduler: greedy
cores: 64

